- name: Provision Minecraft server
  hosts: all
  become: yes
  tasks:
    - name: Update system packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install Java Development Kit (JDK) 8
      apt:
        name: openjdk-17-jdk-headless
        state: present

    - name: Create Minecraft server directory
      file:
        path: /home/ubuntu/minecraft-server
        state: directory
        owner: ubuntu
        group: ubuntu

    - name: Download Minecraft server
      get_url:
        url: https://piston-data.mojang.com/v1/objects/8f3112a1049751cc472ec13e397eade5336ca7ae/server.jar
        dest: /home/ubuntu/minecraft-server/server.jar

    - name: Set eula.txt file
      copy:
        content: "eula=true"
        dest: /home/ubuntu/minecraft-server/eula.txt

    - name: Create systemd service unit for Minecraft
      copy:
        content: |
          [Unit]
          Description=Minecraft Server
          After=network.target

          [Service]
          User=ubuntu
          WorkingDirectory=/home/ubuntu/minecraft-server
          ExecStart=/usr/bin/java -Xmx1024M -Xms1024M -jar server.jar nogui
          Restart=always
          RestartSec=3

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/minecraft.service

    - name: Enable and start the Minecraft service
      systemd:
        name: minecraft
        state: started
        enabled: yes
